# Generated by Django 2.1.5 on 2019-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='year',
            field=models.PositiveIntegerField(default=2018),
            preserve_default=False,
        ),
    ]
