# Generated by Django 2.1.5 on 2019-01-25 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20190125_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendations',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='recommendations',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
