# Generated by Django 2.1.5 on 2019-01-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20190125_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
