# Generated by Django 2.1 on 2019-02-12 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20190127_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
